version: "3.7"

services:

  node:
    container_name: subspace-node
    image: tinnguyen1602/subnode:6-11
    volumes:
      - node-data:/var/subspace:rw
    ports:
      - "0.0.0.0:30339:30339"
      - "0.0.0.0:30439:30439"
    expose:
      - "9615/tcp"
    restart: unless-stopped
    command: [
      "--chain", "gemini-3g",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--blocks-pruning", "256",
      "--state-pruning", "archive",
      "--port", "30339",
      "--dsn-listen-on", "/ip4/0.0.0.0/tcp/30439",
      "--rpc-cors", "all",
      "--rpc-methods", "unsafe",
      "--rpc-external",
      "--no-private-ipv4",
      "--validator",
      "--prometheus-external",
      "--prometheus-port", "9615",
      "--name", "tinboy"
    ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 5

  farmer:
    container_name: subspace-farmer
    depends_on:
      node:
        condition: service_healthy
    image: tinnguyen1602/subfarm:6-11
    volumes:
      - farmer-data:/var/subspace:rw
    ports:
      - "0.0.0.0:30539:30539"
    restart: unless-stopped
    command: [
      "farm",
      "--node-rpc-url", "ws://subspace-node:9944",
      "--listen-on", "/ip4/0.0.0.0/tcp/30539",
      "--reward-address", "stBZcdDHSLpZccr12j4Rdqan8T7YGfxWJzEcfnU7v2KodyHHw",
      "path=/var/subspace,size=50G",

    ]
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=tinboy
      - GF_SECURITY_ADMIN_PASSWORD=Tinboy
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=false
    restart: unless-stopped
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    expose:
      - "9090/tcp"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

volumes:
  node-data:
  farmer-data:
  grafana_data:
  prometheus_data:
